### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by luciusbono** [tech-otaku/macos-desktop#1]
First of all, thank you so much for your amazing blog post and this excellent script. We'd like to use your script in production for our macOS deployment at Mozilla (with full attribution of course), but wondered how you'd like to license this project. 

Would you be willing to provide a license file for this project?

**Comment by tech-otaku** [comment]
Hi Lucius,

Thank you for your comments and your interest in using the script. As such, I have added an MIT License to the repository. 

Regards, Steve.

**Comment by luciusbono** [comment]
Thank you Steve!
