### ISSUE TITLE
Doesn't work with Catalina

### ISSUE THREAD

**Issue by n3philim** [tech-otaku/macos-desktop#2]
Hey! We branched this over at Mozilla, and we're starting our early-phase 10.15 Catalina testing.

Right now the script isn't working -- we've started working on trying to get things sorted out so hopefully it'll work and made the following changes in our fork: https://github.com/mozilla/macos-desktop/pull/1/files

If we figure out what else is going on to get this working in Catalina we'll let you know.

**Comment by tech-otaku** [comment]
Thanks for letting me know.

Am having to wait for the release of the Catalina public beta – sometime in July I believe – before I'm able to test the script with 10.15.

Regards, Steve.

**Comment by tech-otaku** [comment]
Having just installed the Catalina beta, a cursory glance shows significant changes to the values stored in the `data` table of the `desktoppicture` database. Am working on trying to get a handle on these changes and how best to deal with them.

Regards, Steve

**Comment by tech-otaku** [comment]
Am still testing [set-desktop-catalina.sh](https://github.com/tech-otaku/macos-desktop/blob/master/set-desktop-catalina.sh) against the Catalina Beta (19A487l), but so far so good.

Regards, Steve
