### ISSUE TITLE
I keep getting an error

### ISSUE THREAD

**Issue by GabeShack** [tech-otaku/macos-desktop#4]
Result of command:
Error: unable to open database "/Library/Application Support/Dock/desktoppicture.db": unable to open database file
/Library/Application Support/JAMF/set-desktop-mojave.sh: line 100: [: -ge: unary operator expected
Error: unable to open database "/Library/Application Support/Dock/desktoppicture.db": unable to open database file
/Library/Application Support/JAMF/set-desktop-mojave.sh: line 107: [: -ge: unary operator expected
Error: unable to open database "/Library/Application Support/Dock/desktoppicture.db": unable to open database file
[message repeats 8 times]
The Desktop image has been set to /Library/Desktop Pictures/Solar Gradients.heic.

**Comment by tech-otaku** [comment]
`/Library/Application Support/Dock/desktoppicture.db` is the SQLite database defined by Apple that stores the Desktop image. If it now longer exists,  you can create a new empty one with `killall Dock`  from the command line.
